// AUTO-GENERATED by scripts/copy-builtin-packages.ts (issue #1208). Do not edit by hand.
//
// Ambient bridge so the documented bare specifier `@bastani/workflows` (and its
// `builtin/*` submodules) type-check in installed packages that depend only on
// @bastani/atomic. Runtime resolution is unchanged: Atomic's jiti virtual-module
// loader still supplies the real SDK when workflow files load; these declarations
// only affect `tsc`. Each module is declared in exactly one file to avoid
// TS2666 / duplicate-identifier errors.

declare module "@bastani/workflows" {
	export * from "@bastani/atomic/workflows";
}

declare module "@bastani/workflows/builtin" {
	export * from "@bastani/atomic/workflows/builtin";
}

declare module "@bastani/workflows/builtin/adversarial-verification" {
	export * from "@bastani/atomic/workflows/builtin/adversarial-verification";
	export { default } from "@bastani/atomic/workflows/builtin/adversarial-verification";
}

declare module "@bastani/workflows/builtin/classify-and-act" {
	export * from "@bastani/atomic/workflows/builtin/classify-and-act";
	export { default } from "@bastani/atomic/workflows/builtin/classify-and-act";
}

declare module "@bastani/workflows/builtin/fan-out-and-synthesize" {
	export * from "@bastani/atomic/workflows/builtin/fan-out-and-synthesize";
	export { default } from "@bastani/atomic/workflows/builtin/fan-out-and-synthesize";
}

declare module "@bastani/workflows/builtin/generate-and-filter" {
	export * from "@bastani/atomic/workflows/builtin/generate-and-filter";
	export { default } from "@bastani/atomic/workflows/builtin/generate-and-filter";
}

declare module "@bastani/workflows/builtin/goal" {
	export * from "@bastani/atomic/workflows/builtin/goal";
	export { default } from "@bastani/atomic/workflows/builtin/goal";
}

declare module "@bastani/workflows/builtin/loop-until-done" {
	export * from "@bastani/atomic/workflows/builtin/loop-until-done";
	export { default } from "@bastani/atomic/workflows/builtin/loop-until-done";
}

declare module "@bastani/workflows/builtin/open-claude-design" {
	export * from "@bastani/atomic/workflows/builtin/open-claude-design";
	export { default } from "@bastani/atomic/workflows/builtin/open-claude-design";
}

declare module "@bastani/workflows/builtin/ralph" {
	export * from "@bastani/atomic/workflows/builtin/ralph";
	export { default } from "@bastani/atomic/workflows/builtin/ralph";
}

declare module "@bastani/workflows/builtin/tournament" {
	export * from "@bastani/atomic/workflows/builtin/tournament";
	export { default } from "@bastani/atomic/workflows/builtin/tournament";
}
